language: python
python:
  - 2.7
before_install:
  - sudo apt-get install gfortran liblapack-dev
before_script:
  - cmake -DWITH_LIBINT=no .
  - make
script:
  - ctest --output-on-failure -E test_sto_mg6
notifications:
  email: false
