language: python
python:
  - 2.7
env:
  # Test all fast tests in Debug build:
  - TEST_LIBINT="no"  TEST_SLOW="no"  BUILD_TYPE="Debug"
  # Test all fast tests in Debug build with libint:
  - TEST_LIBINT="yes" TEST_SLOW="no"  BUILD_TYPE="Debug"
  # Test all slow tests in Release build (to make them run faster):
  - TEST_LIBINT="no"  TEST_SLOW="yes" BUILD_TYPE="Release"
before_install:
  - sudo apt-get install gfortran liblapack-dev
  - if [ "${TEST_LIBINT}" == "yes" ]; then
      git clone https://github.com/qsnake/libint.git;
      pushd libint;
      ./configure --prefix=/usr > conf_log;
      make > make_log;
      sudo make install;
      popd;
    fi
before_script:
  - cmake -DWITH_LIBINT=${TEST_LIBINT} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .
  - make
script:
  - if [ "${TEST_SLOW}" == "yes" ]; then
      ctest --output-on-failure -L slow;
    else
      ctest --output-on-failure -LE slow;
    fi
notifications:
  email: false
