language: python
python:
  - 2.7
env:
  - TEST_LIBINT="no"
matrix:
  include:
    - python: 2.7
      env: TEST_LIBINT="yes"
before_install:
  - sudo apt-get install gfortran liblapack-dev
  - if [ "${TEST_LIBINT}" == "yes" ]; then
      git clone https://github.com/qsnake/libint.git;
      pushd libint;
      ./configure --prefix=/usr > conf_log;
      make > make_log;
      sudo make install;
      popd;
    fi
before_script:
  - cmake -DWITH_LIBINT=${TEST_LIBINT} .
  - make
script:
  - ctest --output-on-failure -E test_sto_mg6
notifications:
  email: false
